<%@ Page Language="C#" AutoEventWireup="true" MaintainScrollPositionOnPostback="true" CodeBehind="UserChangeEntity.aspx.cs" Inherits="Web.lqnew.opePages.UserChangeEntity" %>

<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">

<html xmlns="http://www.w3.org/1999/xhtml">
<head runat="server">
    <title id="Lang_UserChangeEntityBatch">用户批量转单位</title>
    <script src="../JS/LangueSwitch.js" type="text/javascript"></script>
    <script src="../js/dragwindow.js" type="text/javascript"></script>
    <script type="text/javascript">
        function bindData() {
            document.getElementById("divScrollValue").value = document.getElementById("Entity_Left").scrollTop + "," + document.getElementById("Entity_Right").scrollTop;
        }

        function ScrollToSelectNode() {
            var sv = "<%=ScrollValue%>";
                                  document.getElementById("Entity_Left").scrollTop = sv.split(',')[0];
                                  document.getElementById("Entity_Right").scrollTop = sv.split(',')[1];
                              }
    </script>
</head>
<body onload="ScrollToSelectNode()">
    <div id="Lang_UserEntityChangeBatch" style="text-align: center; font-size: large; font-weight: bold; margin-top: 20px">用户单位批量转移</div>
    <div style="text-align: right"><a id="Lang_ViewChangeLog" href="UserChangeLog.aspx">查看历史记录</a><a id="Lang_ChangeRecover" href="UserChangeRecover.aspx" style="margin-left: 10px">恢复数据</a></div>
    <form id="UserChangeEntity" runat="server" onsubmit="bindData()">
        <div style="width: 700px; margin-left: 20px">
            <%--<asp:ScriptManager ID="ScriptManager1" runat="server">
            </asp:ScriptManager>
    <asp:UpdatePanel ID="UpdatePanel1" runat="server">
    <ContentTemplate>--%>
            <div id="Entity_Left" style="width: 300px; height: 385px; border: 1px; border-style: solid; cursor: default; overflow: auto">
                <asp:TreeView ID="TreeView_Left" runat="server" ShowLines="true" NodeStyle-Width="100%"
                    LineImagesFolder="~/TreeLineImages" Font-Size="14px" ForeColor="Black"
                    OnSelectedNodeChanged="TreeView_Left_SelectedNodeChanged">
                    <HoverNodeStyle BackColor="#99FF99" />
                    <SelectedNodeStyle Font-Bold="True" ForeColor="#0033CC" Font-Size="Larger"
                        BorderColor="#99FF99" BorderStyle="Solid"></SelectedNodeStyle>
                </asp:TreeView>
            </div>
            <div id="Entity_Right" style="float: left; margin-top: -385px; margin-left: 400px; width: 300px; height: 385px; border: 1px; border-style: solid; cursor: default; overflow: auto">
                <asp:TreeView ID="TreeView_Right" runat="server" ShowLines="true" NodeStyle-Width="100%"
                    LineImagesFolder="~/TreeLineImages" Font-Size="14px" ForeColor="Black"
                    AutoGenerateDataBindings="True"
                    OnSelectedNodeChanged="TreeView_Right_SelectedNodeChanged">
                    <HoverNodeStyle BackColor="#99FF99" />
                    <SelectedNodeStyle Font-Bold="True" ForeColor="#0033CC" Font-Size="Larger"
                        BorderColor="#99FF99" BorderStyle="Solid"></SelectedNodeStyle>
                </asp:TreeView>
            </div>
            <div id="clear" style="clear: both"></div>
            <div style="text-align: center">
                <span id="Lang_IsChangeSelf">是否转移本单位编制</span>:<span id="Lang_Yes">是</span><asp:RadioButton ID="RadioButton_Y" runat="server"
                    GroupName="Radiogroup" />
                <span id="Lang_No">否</span><asp:RadioButton ID="RadioButton_N" runat="server"
                    GroupName="Radiogroup" />
            </div>

            <%-- </ContentTemplate>
    </asp:UpdatePanel>--%>

            <div>
                <div style="width: 50%; float: left; text-align: right">
                    <asp:Label ID="Label1" runat="server" ForeColor="#FF3300"></asp:Label></div>
                <!---------------------------xzj--2018/6/28--添加margin-top,margin-right------------------>
                <div style="width: 50%; float: right; margin-top: 10px;margin-right:50px">
                <!---------------------------xzj--2018/6/28--添加margin-top,margin-right------------------>
                    <asp:Button ID="Button1" runat="server" Text="确定" OnClick="Button1_Click" />
                    <!---------------------------xzj--2018/6/28--添加OnClientClick（）函数------------------>
                    <asp:Button ID="Button2" runat="server" Text="取消" OnClick="Button2_Click" OnClientClick="window.parent.parent.mycallfunction('UserChangeEntity1',800, 800)" />
                    <!---------------------------xzj--2018/6/28--添加OnClientClick（）函数------------------>
                </div>
                <div id="clear2" style="clear: both"></div>
            </div>
            <asp:HiddenField ID="divScrollValue" runat="server" />
        </div>
    </form>
</body>
</html>
