includesrcipt(basePath + 'JQuery/jquery-1.5.2.js');
includesrcipt(basePath + 'JS/Config.js');
includesrcipt(basePath + 'JS/Layers.js');
includesrcipt(basePath + 'JS/Tools1.js');
includesrcipt(basePath + 'JS/ToolBar.js');
includesrcipt(basePath + "JS/LayerVml.js");
includesrcipt(basePath + "lqCommonJS/conmonjs.js")
includesrcipt(basePath + "lqnew/js/toolbutton.js")
includesrcipt(basePath + "lqnew/js/trace.js")
includesrcipt(basePath + "lqnew/js/mark.js")